VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IBe"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Function OneOf(ParamArray vals() As Variant)

End Function

Public Function GreaterThan(value As Double) As Boolean

End Function

Public Function GreaterThanOrEqualTo(value As Double) As Boolean

End Function

Public Function LessThan(value As Double) As Boolean

End Function

Public Function LessThanOrEqualTo(value As Double) As Boolean

End Function

Public Function EqualTo(value As Variant) As Boolean

End Function

Public Function Something() As Boolean

End Function

Public Function Between(lowerVal As Double, higherVal As Double) As Boolean

End Function


Public Function InDataStructure(dataStructure As Variant, Optional method As flMethod = flRecursive) As Boolean

End Function

