VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IFluentFunction"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Get Meta() As IMetaFluentFunction
End Property

Public Function OfCalledFunction( _
    ByVal functionName As String, _
    Optional ByVal testingInput1 As Variant, Optional ByVal testingInput2 As Variant, _
    Optional ByVal testingInput3 As Variant, Optional ByVal testingInput4 As Variant, _
    Optional ByVal testingInput5 As Variant, Optional ByVal testingInput6 As Variant, _
    Optional ByVal testingInput7 As Variant, Optional ByVal testingInput8 As Variant, _
    Optional ByVal testingInput9 As Variant, Optional ByVal testingInput10 As Variant, _
    Optional ByVal testingInput11 As Variant, Optional ByVal testingInput12 As Variant, _
    Optional ByVal testingInput13 As Variant, Optional ByVal testingInput14 As Variant, _
    Optional ByVal testingInput15 As Variant, Optional ByVal testingInput16 As Variant, _
    Optional ByVal testingInput17 As Variant, Optional ByVal testingInput18 As Variant, _
    Optional ByVal testingInput19 As Variant, Optional ByVal testingInput20 As Variant, _
    Optional ByVal testingInput21 As Variant, Optional ByVal testingInput22 As Variant, _
    Optional ByVal testingInput23 As Variant, Optional ByVal testingInput24 As Variant, _
    Optional ByVal testingInput25 As Variant, Optional ByVal testingInput26 As Variant, _
    Optional ByVal testingInput27 As Variant, Optional ByVal testingInput28 As Variant, _
    Optional ByVal testingInput29 As Variant, Optional ByVal testingInput30 As Variant, _
    Optional ByVal returnTypeIsObject As Boolean = False _
) As IUnitFluentOf
End Function

Public Function OfCalledMethod( _
    methodObject As Object, _
    methodName As String, _
    Optional ByVal testingInput1 As Variant, Optional ByVal testingInput2 As Variant, _
    Optional ByVal testingInput3 As Variant, Optional ByVal testingInput4 As Variant, _
    Optional ByVal testingInput5 As Variant, Optional ByVal testingInput6 As Variant, _
    Optional ByVal testingInput7 As Variant, Optional ByVal testingInput8 As Variant, _
    Optional ByVal testingInput9 As Variant, Optional ByVal testingInput10 As Variant, _
    Optional ByVal testingInput11 As Variant, Optional ByVal testingInput12 As Variant, _
    Optional ByVal testingInput13 As Variant, Optional ByVal testingInput14 As Variant, _
    Optional ByVal testingInput15 As Variant, Optional ByVal testingInput16 As Variant, _
    Optional ByVal testingInput17 As Variant, Optional ByVal testingInput18 As Variant, _
    Optional ByVal testingInput19 As Variant, Optional ByVal testingInput20 As Variant, _
    Optional ByVal testingInput21 As Variant, Optional ByVal testingInput22 As Variant, _
    Optional ByVal testingInput23 As Variant, Optional ByVal testingInput24 As Variant, _
    Optional ByVal testingInput25 As Variant, Optional ByVal testingInput26 As Variant, _
    Optional ByVal testingInput27 As Variant, Optional ByVal testingInput28 As Variant, _
    Optional ByVal testingInput29 As Variant, Optional ByVal testingInput30 As Variant, _
    Optional ByVal returnTypeIsObject As Boolean = False _
) As IUnitFluentOf
End Function
