VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IHave"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Function LengthOf(Value As Double) As Boolean

End Function

Public Function MaxLengthOf(Value As Double) As Boolean

End Function

Public Function MinLengthOf(Value As Double) As Boolean

End Function

Public Function LengthBetween(LowValue As Double, HighValue As Double) As Boolean

End Function
