VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IHave"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Function LengthOf(ByVal Value As Double) As Boolean

End Function

Public Function MaxLengthOf(ByVal Value As Double) As Boolean

End Function

Public Function MinLengthOf(ByVal Value As Double) As Boolean

End Function

Public Function LengthBetween(ByVal LowValue As Double, ByVal HighValue As Double) As Boolean

End Function
