VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IMeta"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Set Meta(value As cMeta)

End Property

Public Property Get Meta() As cMeta

End Property

Public Property Set setPrintSettings(value As cPrintSettings)

End Property
