VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IPrinting"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Get TestCollection() As Collection

End Property

Public Property Let FluentPath(value As String)

End Property

Public Function getFluentPath(FluentPath As String, shouldStr As String, test As cTest)

End Function
