VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IPrintSettings"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Let TestName(value As String)

End Property

Public Property Get TestName() As String

End Property

Public Property Get TestCollection() As Collection

End Property

Public Sub printTestCounts()

End Sub
