VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IPrintSettings"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Let TESTNAME(value As String)

End Property

Public Property Get TESTNAME() As String

End Property

Public Property Get TestCollection() As Collection

End Property

Public Property Let TestCount(value As Long)
    
End Property

Public Property Get TestCount() As Long
    
End Property

Public Property Let CATEGORY(value As String)
    
End Property

Public Property Get CATEGORY() As String
    
End Property


'Public Sub printTestCounts()
'
'End Sub
