VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IPrintExpr"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Get TestCollection() As Collection

End Property

Public Property Let FluentPath(ByVal value As String)

End Property

Public Property Get Expressions() As IExpressions

End Property

Public Property Let CategorySet(ByVal value As Boolean)

End Property

Public Property Let NameSet(ByVal value As Boolean)

End Property
