VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ISetTestFuncsAndValue"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Set SetTestFunc(ByVal value As cTestingFunctions)
End Property

Public Property Let TestValue(ByVal value As Variant)
End Property

Public Property Set TestValue(ByVal value As Variant)
End Property

