VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ISetExpressionAndValue"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Set SetExpr(Value As cExpressions)

End Property

Public Property Let TestValue(Value As Variant)

End Property

Public Property Set TestValue(Value As Variant)

End Property

