VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITestDev"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Let NegateValue(value As Boolean)
End Property

Public Property Get NegateValue() As Boolean
End Property

Public Property Let resultNumber(value As Long)
End Property

Public Property Get resultNumber() As Long
End Property
