VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITest"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Let testingValue(value As Variant)
End Property

Public Property Set testingValue(value As Variant)
End Property

Public Property Get testingValue() As Variant
End Property

Public Property Let testingInput(value As Variant)
End Property

Public Property Set testingInput(value As Variant)
End Property

Public Property Get testingInput() As Variant
End Property

Public Property Let LowerVal(value As Double)
End Property

Public Property Get LowerVal() As Double
End Property

Public Property Let HigherVal(value As Double)
End Property

Public Property Get HigherVal() As Double
End Property

Public Property Let FluentPath(value As String)
End Property

Public Property Get FluentPath() As String
End Property

Public Property Let Result(value As Variant)
End Property

Public Property Get Result() As Variant
End Property

Public Property Let functionName(value As String)
End Property

Public Property Get functionName() As String
End Property

Public Property Let StrTestValue(value As String)
End Property

Public Property Get StrTestValue() As String
End Property

Public Property Let StrTestInput(value As String)
End Property

Public Property Get StrTestInput() As String
End Property

Public Property Let HasNull(value As Boolean)
End Property

Public Property Get HasNull() As Boolean
End Property

Public Property Let Category(value As String)
End Property

Public Property Get Category() As String
End Property

Public Property Let TestName(value As String)
End Property

Public Property Get TestName() As String
End Property
