VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IToString"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Let WrapChar(value As String)
End Property

Public Property Get WrapChar() As String
End Property

Public Function WrapIfString(value As Variant)
End Function
